//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorCycleWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerProducts
    {
        public int DealerProductId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Dealers Dealers { get; set; }
        public virtual Products Products { get; set; }
    }
}
